init:
  - git config --global core.autocrlf input

skip_branch_with_pr: true

image: Visual Studio 2019
environment:  
  BENCHMARKS: on

branches:
  only:
    - master    

install:
  - cmd: choco install gitversion.portable -y

before_build:
  - ps: gitversion /l console /output buildserver

build:
  verbosity: detailed

build_script:
- cmd: dotnet build -c Release
- cmd: dotnet pack .\src\Simple.Arena\Simple.Arena.csproj -c Release /p:Version=%GitVersion_NuGetVersionV2%  --output %APPVEYOR_BUILD_FOLDER%/artifacts/
test_script:
- cmd: dotnet test
artifacts:
- path: artifacts/*

deploy:
  provider: NuGet
  api_key:
    secure: iY8d/s4pWv+n4fp96yoTGDOD3PVJX45uNj7XEkSiXsbZkibxd3GNmKharbGraEJX  
  skip_symbols: false
  artifact: /.*\.nupkg/