init:
  - git config --global core.autocrlf input

skip_tags: true
skip_branch_with_pr: true

image: Visual Studio 2019
environment:  
  BENCHMARKS: on

branches:
  only:
    - master    

install:
  - cmd: choco install gitversion.portable -y

before_build:
  - ps: gitversion /l console /output buildserver

build:
  verbosity: detailed
  
build_script:
- cmd: dotnet build -c Release
- ps: dotnet pack .\src\Simple.Arena\Simple.Arena.csproj -c Release -p:Version $env:GitVersion_NuGetVersionV2 --output $env:APPVEYOR_BUILD_FOLDER/artifacts/
test_script:
- cmd: dotnet test
artifacts:
- path: artifacts/*

deploy_script:
- ps: >-
    if ($env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT -eq "false") {
       Write-Host "Not a pull request!"
    }
