init:
  - git config --global core.autocrlf input

skip_tags: true
skip_branch_with_pr: true

image: Visual Studio 2019
environment:  
  BENCHMARKS: on

branches:
  only:
    - master    

install:
  - cmd: choco install gitversion.portable -y

before_build:
  - ps: gitversion /l console /output buildserver

build:
  verbosity: detailed
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '${GitVersion_NuGetVersionV2}'

build_script:
- cmd: dotnet build -c Release
- cmd: dotnet pack .\src\Simple.Arena\Simple.Arena.csproj -c Release --output %APPVEYOR_BUILD_FOLDER%/artifacts/
test_script:
- cmd: dotnet test
artifacts:
- path: artifacts/*

deploy:
  - provider: NuGet
    api_key:
      secure: iY8d/s4pWv+n4fp96yoTGDOD3PVJX45uNj7XEkSiXsbZkibxd3GNmKharbGraEJX  
    skip_symbols: false
    artifact: /.*\.nupkg/
  
  - provider: GitHub
    artifact: artifacts/*           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
